### PR TITLE
Improvements

### PR DESCRIPTION
**Pull request by juhlig**

### CODE REVIEW

**Comment by Maria-12648430** [comment]
Wow, this will take me a while to review ^^;

Looking good from a first skim, much cleaner than the first draft. And I kinda like what you did to the tests 🤗

**Comment by Maria-12648430** [comment]
As a first thing, add your name to the copyright lines ;)

**Comment by juhlig** [comment]
Take your time :)

**Comment by juhlig** [comment]
Copyright updated :)

**Comment by Maria-12648430** [comment]
> Copyright updated :)

Good, welcome officially aboard ;)

**Review by Maria-12648430 — APPROVED** [review]
Looks good. The tests cover everything, so I think we're good.

**Pull request merged**
