### PR TITLE
Docs and refactoring

### PR DESCRIPTION
**Pull request by Maria-12648430**
This PR is mostly an overhaul of the entire edoc.
The `join/3` function has been removed in favor of `append/3` and `prepend/3`, and together with `join/2` learned some new tricks ;)

### CODE REVIEW

**Comment by juhlig** [comment]
Whoa :) Nice work, but it will take me literally _ages_ to proofread this =^^=

**Comment by Maria-12648430** [comment]
> it will take me literally _ages_ to proofread this =^^=

What are you waiting for then, get to it ;)))

**Comment by juhlig** [comment]
> What are you waiting for then, get to it ;)))

Yeah, sure ;) Already on it.

**Review by juhlig — APPROVED** [review]
All looking very nice :)
Good job on the edoc stylesheet ^^; I think this is the ebst you can currently make out of it without writing a custom layouter =^^=

**Comment by Maria-12648430** [comment]
Thanks :)

**Pull request merged**
